// Mocks generated by Mockito 5.4.6 from annotations
// in driver/test/features/earnings/earnings_dashboard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:driver/core/providers/region_provider.dart' as _i2;
import 'package:driver/features/earnings/providers/earnings_provider.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRegionSettings_0 extends _i1.SmartFake
    implements _i2.RegionSettings {
  _FakeRegionSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EarningsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEarningsProvider extends _i1.Mock implements _i3.EarningsProvider {
  MockEarningsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  List<Map<String, dynamic>> get banks =>
      (super.noSuchMethod(
            Invocation.getter(#banks),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  List<dynamic> get payoutHistory =>
      (super.noSuchMethod(
            Invocation.getter(#payoutHistory),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  Map<String, dynamic> get ratingData =>
      (super.noSuchMethod(
            Invocation.getter(#ratingData),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> get earningsData =>
      (super.noSuchMethod(
            Invocation.getter(#earningsData),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  double get availableBalance =>
      (super.noSuchMethod(
            Invocation.getter(#availableBalance),
            returnValue: 0.0,
          )
          as double);

  @override
  double get totalEarnings =>
      (super.noSuchMethod(Invocation.getter(#totalEarnings), returnValue: 0.0)
          as double);

  @override
  List<dynamic> get weeklyChartData =>
      (super.noSuchMethod(
            Invocation.getter(#weeklyChartData),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> get monthlyChartData =>
      (super.noSuchMethod(
            Invocation.getter(#monthlyChartData),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  String get currency =>
      (super.noSuchMethod(
            Invocation.getter(#currency),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDashboard, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadEarningsData() =>
      (super.noSuchMethod(
            Invocation.method(#loadEarningsData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setDailyGoal(double? goal) => super.noSuchMethod(
    Invocation.method(#setDailyGoal, [goal]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadBanks() =>
      (super.noSuchMethod(
            Invocation.method(#loadBanks, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> requestPayout(
    double amount, {
    String? accountNumber,
    String? bankCode,
    String? currency,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestPayout,
              [amount],
              {#accountNumber: accountNumber, #bankCode: bankCode, #currency: currency},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> verifyAccount(String? accountNumber, String? bankCode) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAccount, [accountNumber, bankCode]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#verifyAccount, [accountNumber, bankCode]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> updateBankDetails(Map<String, dynamic>? details) =>
      (super.noSuchMethod(
            Invocation.method(#updateBankDetails, [details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> fetchStripeDashboardUrl() =>
      (super.noSuchMethod(
            Invocation.method(#fetchStripeDashboardUrl, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#fetchStripeDashboardUrl, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> loadRatingDistribution() =>
      (super.noSuchMethod(
            Invocation.method(#loadRatingDistribution, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadPayoutHistory() =>
      (super.noSuchMethod(
            Invocation.method(#loadPayoutHistory, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RegionProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegionProvider extends _i1.Mock implements _i2.RegionProvider {
  MockRegionProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RegionCode get code =>
      (super.noSuchMethod(
            Invocation.getter(#code),
            returnValue: _i2.RegionCode.ng,
          )
          as _i2.RegionCode);

  @override
  _i2.RegionSettings get current =>
      (super.noSuchMethod(
            Invocation.getter(#current),
            returnValue: _FakeRegionSettings_0(
              this,
              Invocation.getter(#current),
            ),
          )
          as _i2.RegionSettings);

  @override
  String get currency =>
      (super.noSuchMethod(
            Invocation.getter(#currency),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
          )
          as String);

  @override
  String get symbol =>
      (super.noSuchMethod(
            Invocation.getter(#symbol),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#symbol),
            ),
          )
          as String);

  @override
  String get unitSystem =>
      (super.noSuchMethod(
            Invocation.getter(#unitSystem),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#unitSystem),
            ),
          )
          as String);

  @override
  String get apiRegionKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiRegionKey),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#apiRegionKey),
            ),
          )
          as String);

  @override
  bool get isNigeria =>
      (super.noSuchMethod(Invocation.getter(#isNigeria), returnValue: false)
          as bool);

  @override
  bool get isChicago =>
      (super.noSuchMethod(Invocation.getter(#isChicago), returnValue: false)
          as bool);

  @override
  List<_i2.RegionSettings> get allRegions =>
      (super.noSuchMethod(
            Invocation.getter(#allRegions),
            returnValue: <_i2.RegionSettings>[],
          )
          as List<_i2.RegionSettings>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> setRegion(_i2.RegionCode? code) =>
      (super.noSuchMethod(
            Invocation.method(#setRegion, [code]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void detectFromLocation(double? lat, double? lng) => super.noSuchMethod(
    Invocation.method(#detectFromLocation, [lat, lng]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
